Bitte geben Sie die Infonachricht für "Bitte einloggen" ein:
<br /><input type="text" name="VALUE[1]" value="REX_VALUE[1]" size="30" />

<br /><br />Bitte geben Sie die Infonachricht für "Sie sind nun ausgeloggt" ein:
<br /><input type="text" name="VALUE[2]" value="REX_VALUE[2]" size="30" />

<br /><br />Bitte geben Sie die Infonachricht für "Login ist fehlgeschlagen" ein:
<br /><input type="text" name="VALUE[3]" value="REX_VALUE[3]" size="30" />

<br /><br />Bitte geben Sie die Infonachricht für "Sie sind nun eingeloggt" ein:
<br /><input type="text" name="VALUE[4]" value="REX_VALUE[4]" size="30" />

<br /><br />Bitte geben Sie Bezeichnung für "Login" ein:
<br /><input type="text" name="VALUE[6]" value="REX_VALUE[6]" size="30" />

<br /><br />Bitte geben Sie Bezeichnung für "Passwort" ein:
<br /><input type="text" name="VALUE[7]" value="REX_VALUE[7]" size="30" />


<br /><br />Bitte geben Sie Bezeichnung für "eingeloggt bleiben" ein:
<br /><input type="text" name="VALUE[8]" value="REX_VALUE[8]" size="30" />

